### PR TITLE
Fixes

### LINKED ISSUE #3: Fixes/updates for v2
Hi @abdulrauf11, please make the following updates to the existing application.

- The header font for "Career Connections" should be `Ropa Soft Pro Extra Bold Italic` (this currently looks too light-weight)
- Tabs at the top: The text color for the _selected_ tab should always be white on a dark blue background (currently the text on the selected "My Story" tab is gray on dark blue.)
- Please add `:active` states to the `My Story` and `My Career Path` buttons. When active (or "pressed"), scale the button to 95% of it's original size and darken the background color by 10%.
- Update the text content and folder structure using the table below for eight real profiles. Continue to use duplicate content for the remaining profiles to maintain a total of twelve profiles (eight real profiles + four placeholders). Given that some roles have lengthy titles that do not fit on the carousel buttons, please create and use abbreviated versions for display in the bottom carousel. Again, thank you for anticipating this and separating those in the JSON structure!

Provider | Role | Quote
-- | -- | --
David Oh | Chief medical officer at Hoxworth Blood Center | Blood is considered to be a drug and we're regulated by the FDA. My job is to make sure that the blood that we collect, process and distribute is safe for the donors and for the recipients. I think of blood donation as a donor giving freely of their life essence and creating a link with someone in need, which is inspiring!
John Bush | Respiratory therapist | Working in the hospital as a patient transporter gave me a chance to see lots of careers. I knew I wanted to be hands-on with patients. So, I went to Cincinnati State, got my Associate’s degree and passed my medical boards in respiratory therapy. That opened new opportunities for me at the hospital and eventually got me to the sidelines at Cincinnati Bengals games, where I’m part of the emergency action plan to support players. On my best days, I get to help people breathe better and get back to their families.
Lori Crosby | Psychiatrist | We see patients as holistic — with their minds and bodies connected. Behaviors, such as exercise, or how we eat, or when we take medication, might help address a range of concerns. My work focuses on those behaviors. How do we optimize and make it easy for people to do what they need to do to care for their conditions and themselves?
Lori Pierson | Hoxworth Blood Center donor care technician | I assist with collecting blood products to provide hospitals and surgery centers with the supply they need to help individuals who need blood transfusions. I get to know some of the regular donors and learn about their families — I look forward to asking them about how they are doing and to thanking them for giving. These volunteers help the community and save lives, and I love playing a role in that.
Margaret Chamberlain | Radiologic technologist | We are skeleton photographers. Doctors can't see what's going on inside someone’s body, and imaging is the next best thing. My job involves a lot of thinking outside of the box. I may not be able to take an x-ray in a textbook way, because it would make the patient uncomfortable, but I always find a way to get the doctors the information they need without harming the patient or making them feel worse.
Molly Thomas | Pediatric physical therapist | I help young people work with their muscles to move their bodies as well as they can. That looks different for everybody. Without your muscles working together, you would not be able to do things like sit and stand, run and jump. Your muscles are the dynamic part of you. They help you be a person. They’re what makes you fun!
Robert Bohinski, M.D., Ph.D. | Physician and surgeon | There are mechanical aspects of the spine that keep us upright and moving, and there are the parts that interact with our nervous system that keep us out of pain and send healthy signals to our arms and legs. That blend of bones and nerves hooked me as a medical student. I aim to keep people as active as they can be — if you've got a bad spine, it's hard to do anything well.
Misty Vaccariello, LMT | Sports Massage Therapist | Licensed massage therapy is the perfect missing piece in an athlete’s life between orthopedics and physical therapy. I’ve been fortunate to work with hobbyists and professional athletes and return their comfort and mobility without medications. Having the ability to relieve an injured client’s pain and help them get back to their ideal fitness level makes me want to help as many people as I can.

- Lastly, please document the JSON structure in a format that is easy for non-technical users to understand. If you want, you can follow the format in my example table below, or use another format if that's easier. At a minimum, it should describe what each field controls in the application. You can provide this in the README for this repo.

_(FOR EXAMPLE PURPOSES ONLY)_
| Field                | Description                                                                                                                      | Type             | Accepted Format        | Example                                        |
|----------------------|----------------------------------------------------------------------------------------------------------------------------------|------------------|------------------------|------------------------------------------------|
| `id`                 | Unique identifier for the application. This does not appear in the application.                                                  | string           | N/A                    | `"skillsville"`                                |
| `videoSelections`    | List of video selections and associated files for selection by the user.                                                         | array of objects | N/A                    | See indented videoSelections structure below   |
| - `titleDisplay`     | Title of the video displayed on the selection confirmation screen.                                                               | string           | N/A                    | `"Brush your teeth with dinosaurs!"`           |
| - `captionAsset`     | Path to the caption file for the video, which displays at bottom of screen during video playback.                                | string           | VTT                    | `"/assets/captions/captions-1-en-US.vtt"`      |
| - `videoAsset`       | Path to the video file that will play fullscreen after confirmation of selection.                                                | string           | MP4                    | `"/assets/videos/fpo-skillsville.mp4"`         |
| - `thumbnail`        | Path to the thumbnail image representing the video. This image is displayed in the carousel as well as the confirmation screen.  | string           | JPG, PNG               | `"/assets/images/tpt1.png"`                    |

### PR DESCRIPTION
**Pull request by abdulrauf11**
Please review all the changes.

I've documented the JSON structure in the README.md file. Let me know if you want to change any description.

Here's the [preview link](https://cmc-biomed-career-connections-git-fixes-rauf-tech.vercel.app?_vercel_share=ln5IKgG9pXA43PZ7rAty2oLyZfCFeGv9)

### CODE REVIEW

**Review by tnordberg — CHANGES_REQUESTED** [review]
Hi @abdulrauf11, thank you for the updates. The new documentation looks excellent.

It appears that the buttons do not yet utilize the `:active` state. I apologize if my previous description was unclear. I am referring to this CSS state: [https://www.w3schools.com/cssref/sel_active.php](https://www.w3schools.com/cssref/sel_active.php).

Implementing `:active` states is crucial for touchscreen applications, as it provides immediate feedback to users when their finger touches down.

Additionally, could you ensure that the text within the application is not selectable or highlightable? I noticed that at least one field can still be selected: [https://d.pr/v/bDy4Ie](https://d.pr/v/bDy4Ie). You might find the CSS rule `user-select: none;` useful for this purpose.

Otherwise, this is looking great and I look forward to installing in the exhibit.

**Comment by abdulrauf11** [comment]
@tnordberg Ah thanks for clarifying! Should be fixed now

**Review by tnordberg — CHANGES_REQUESTED** [review]
Hi @abdulrauf11, thanks for making these fixes. 

There's one additional touchscreen CSS fix I'd like to request, and apologies for not catching it on the previous review. 

Could you please make sure the images cannot be ghost-dragged when a user clicks/touches then drags the image? This is a browser feature that we always need to disable for exhibits. 

Here's what it looks like in action: https://d.pr/v/T1xuQe

I believe you can use `-webkit-user-drag: none;` to disable this, and globally target all images.

This should be the change edit for this project. Thank you!

**Comment by abdulrauf11** [comment]
Hey @tnordberg, I have pushed the changes. Will keep this in mind for all future projects! Let me know if there's anything else.

**Review by tnordberg — APPROVED** [review]
Great work! Thanks.

**Pull request merged**
